modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "abyssaldecor"
version = "${version}"
displayName = "Abyssal Decor"
authors = ["Starrysock, Pixel Dream Studios"]
description = '''
(Mostly) Vanilla style decorative blocks, (mostly) inspired by Victorian and Lovecraftian themes!
'''
logoFile = "icon.png"

[[dependencies.abyssaldecor]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abyssaldecor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abyssaldecor]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"